image: maven:latest
#inspired by https://gitlab.com/gitlab-examples/maven/simple-maven-example
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository/
    - target/

Build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

# Test stage
test:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test commands here.

IPTest:
  stage: test
  script:
    - mvn -Dtest=h1.IPTest test

TimeTest:
  stage: test
  script:
    - mvn -Dtest=h1.TimeTest test

G6Test:
  stage: test
  script:
    - mvn -Dtest=h3.G6Test test

ExpritTest:
  stage: test
  script:
    - mvn -Dtest=h3.ExpritTest test

ExprTest:
  stage: test
  script:
    - mvn -Dtest=h3.ExprTest test

calcGATest:
  stage: test
  script:
    - mvn -Dtest=h4.calcGATest test

calcVisitorTest:
  stage: test
  script:
    - mvn -Dtest=h4.calcVisitorTest test

calcListenerTest:
  stage: test
  script:
    - mvn -Dtest=h4.calcListenerTest test

callGraphTest:
  stage: test
  script:
    - mvn -Dtest=h5.CallgraphTest test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."